backend:
  name: github
  repo: komatic5/gdcs2
  branch: main
  open_authoring: true

media_folder: /static/media
public_folder: /media
publish_mode: editorial_workflow

fields: &page_fields
  - { label: Draft, name: draft, widget: boolean }
  - { label: Math, name: math, widget: boolean }
  - { label: Title, name: title, widget: string }
  - { label: Weight, name: weight, widget: number }
  - { label: Body, name: body, widget: markdown }

collections:
  - name: guides
    label: Guides
    folder: "content/docs/guides"
    nested:
      depth: 5
      subfolders: false
    fields: *page_fields

  - name: contributing
    label: Contributing
    folder: "content/contributing"
    nested:
      depth: 5
      subfolders: false
    fields: *page_fields
